#Reference for tetsing
#http://superuser.com/questions/640839/how-to-enter-login-information-for-a-website-from-the-linux-command-line

# If directly curl to canvas assignment page, will only show "Redirected"

`#!/bin/bash`

homeworks=$(curl -s -u wang2667 https://canvas.uw.edu/courses/1100121/assignments | hxnormalize -x | hxselect -c -i a.ig-title);

echo "${homeworks[0]}";

# It seems like curl can't get content if it is generated by js, which canvas is currently doing
